parking/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :spots
  resources :reservations
  get 'users/new'

  get 'uers/new'

  get 'main_controller/main'

  root 'spots#index'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users

end

parking/app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :spot 
	belongs_to :reservation_time
	belongs_to :user
	validates :time_range, presence:true

	def is_not_available(start_epoch, end_epoch)
		requested_reservation_start_epoch = requested_datetime.to_time.to_i
		requested_reservation_end_epoch = requested_datetime.to_time.to_i + (3600 * time_range.to_i)

		return requested_reservation_start_epoch.between?(start_epoch + 1, end_epoch - 1) || requested_reservation_end_epoch.between?(start_epoch + 1, end_epoch - 1) || 
				( start_epoch >= requested_reservation_start_epoch && end_epoch <= requested_reservation_end_epoch)
	end
end

parking/app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)
    reserved_spot = Spot.find(@reservation.spot_id)

    if !logged_in?
      flash[:danger] = "You need to log in!"
      redirect_to reserved_spot
      return
    end 

    reserved_spot.reservations.each do |spot_reservation|
      start_epoch = spot_reservation.requested_datetime.to_time.to_i
      end_epoch = spot_reservation.requested_datetime.to_time.to_i + (3600 * spot_reservation.time_range.to_i)

      if @reservation.is_not_available(start_epoch, end_epoch)
        flash[:danger] = 'Reservation cannot be made. This date have been reserved.'
        redirect_to reserved_spot
        return
      end   
    end

    if @reservation.save
      flash[:success] = 'Reservation was successfully created.'
      redirect_to reserved_spot
    else
      flash[:danger] =  @reservation.errors.full_messages
      redirect_to reserved_spot
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    reserved_spot = Spot.find(@reservation.spot_id)
    flash[:success] = 'Reservation was successfully deleted.'
    redirect_to reserved_spot
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:spot_id, :requested_datetime, :time_range, :reservation_time_id, :user_id)
    end
end

parking/app/helpers/reservations_helper.rb
module ReservationsHelper
end

parking/app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>       
<% end %>

parking/app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

parking/app/views/reservations/index.html.erb
<div class="row">
  <div class="col-sm-10 col-sm-offset-1">
    <h1>Listing Reservations</h1>
    <br/>

    <%- if @reservations.none? %>
      <h3 id="table_message">No existing reservations</h3>
    <%- else %>
      <table align="center", class="table table-striped">
        <thead>
          <tr>
            <th class="text-center">Customer</th>
            <th class="text-center">Spot ID</th>
            <th class="text-center">Reservation Date</th>
            <th class="text-center">Duration (h)</th>  
          </tr>
        </thead>

        <tbody>
          <% @reservations.each do |reservation| %>
            <% user = User.find(reservation.user_id) %>
            <tr class="reservations_list_item">
              <td class="text-center"><%= user.name + " " + user.surname %></td>
              <td class="text-center"><%= reservation.spot_id %></td>
              <td class="text-center"><%= reservation.requested_datetime.strftime("%x %H:%M") %></td>
              <td class="text-center"><%= reservation.time_range %></td>
              <% if logged_in? && reservation.user_id == current_user.id %>
                <td><%= link_to 'Cancel', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <% else %>
                <td/>
							<% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %> 
  </div>
</div>
<br>

parking/app/views/reservations/new.html.erb
<%= render 'form' %>