parking/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :spots
  resources :reservations
  get 'users/new'

  get 'uers/new'

  get 'main_controller/main'

  root 'spots#index'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users

end

parking/app/models/spot.rb
class Spot < ActiveRecord::Base
	has_many :reservations

	def self.search(search)
	  if search
	    find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
  	end
	end
end

parking/app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :set_spot, only: [:show, :edit, :update, :destroy]

  def search
  end

  # GET /spots
  # GET /spots.json
  def index
    @spots = Spot.all

    # @reservation_time = ReservationTime.last

    @searched_project = Spot.search(params[:search])

  end

  # GET /spots/1
  # GET /spots/1.json
  def show
    @reservation = Reservation.new(id: @spot.id)
  end

  # GET /spots/new
  def new
    @spot = Spot.new
  end

  # GET /spots/1/edit
  def edit
  end

  # POST /spots
  # POST /spots.json
  def create
    @spot = Spot.new(spot_params)

    @spot.reserved = "no"

    respond_to do |format|
      if @spot.save
        format.html { redirect_to @spot, notice: 'Spot was successfully created.' }
        format.json { render :show, status: :created, location: @spot }
      else
        format.html { render :new }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spots/1
  # PATCH/PUT /spots/1.json
  def update
    respond_to do |format|
      if @spot.update(spot_params)
        format.html { redirect_to @spot, notice: 'Spot was successfully updated.' }
        format.json { render :show, status: :ok, location: @spot }
      else
        format.html { render :edit }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spots/1
  # DELETE /spots/1.json
  def destroy
    @spot.destroy
    respond_to do |format|
      format.html { redirect_to spots_url, notice: 'Spot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spot
      @spot = Spot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def spot_params
      # params.require(:spot).permit(:id_number, :reserved)
      params.fetch(:spot, {})
    end
end

parking/app/helpers/spots_helper.rb
module SpotsHelper
end

parking/app/views/spots/_form.html.erb
<%= form_for(@spot) do |f| %>
  <% if @spot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spot.errors.count, "error") %> prohibited this spot from being saved:</h2>

      <ul>
      <% @spot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

parking/app/views/spots/index.html.erb
<% if params["datetime"] %>
  <% searched_datatime = DateTime.new(params["datetime"]["parameter(1i)"].to_i, params["datetime"]["parameter(2i)"].to_i, params["datetime"]["parameter(3i)"].to_i, params["datetime"]["parameter(4i)"].to_i, params["datetime"]["parameter(5i)"].to_i, 0) %>
  <% searched_duration = params["duration"] %>
<% else %>
  <% searched_datatime = DateTime.now %>
  <% searched_duration = 1 %>
<% end %>

<div class="row">
  <div class="col-sm-10 col-sm-offset-1">
    <h1>Parking spots</h1>
    <br/>
    <div class="well">
      <%= form_tag(spots_path, method: "get") do %>
        <%= datetime_select :datetime, :parameter, order: [:day, :month, :year], default: searched_datatime, minute_step: 60 %>
        <%= text_field_tag :duration, searched_duration, style: 'margin-left:10px' %>
        <%= submit_tag "Search", style: 'margin-left:20px' %>
      <% end %>
    </div>
  </div>
</div>

<table align="center">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% for i in (0...8) %>
      <% if i % 2 == 0 %>
        <tr class="road"/>
      <% end %>
      <tr>
        <% @spots.each do |spot| %>
          <% if spot.y == i %>
            <% is_reserved = 0 %>
            <% spot.reservations.each do |reservation| %>

              <% if searched_duration.to_i < 1 %>
                <% searched_duration = "1" %>
              <% end %>

              <% single_reservation_start_epoch = reservation.requested_datetime.to_time.to_i %>
              <% single_reservation_end_epoch = reservation.requested_datetime.to_time.to_i + (3600 * reservation.time_range.to_i) %>
              <% start_epoch = searched_datatime.to_time.to_i %>
              <% end_epoch = searched_datatime.to_time.to_i + (3600 * searched_duration.to_i) %>

              <%  if single_reservation_start_epoch.between?(start_epoch + 1, end_epoch - 1) || single_reservation_end_epoch.between?(start_epoch + 1, end_epoch - 1) ||
                ( start_epoch >= single_reservation_start_epoch && end_epoch <= single_reservation_end_epoch) %>
                <% is_reserved = 1 %>
                <% break %>
              <% end %>
            <% end %>

            <% if is_reserved == 0 %>
              <td><%= link_to '', spot, :class => 'seatNumber' %></td>
            <% else %>
              <td><%= link_to '', spot, :class => 'seatNumberUnavailable' %></td>
            <% end %>
            <% if spot.x == 9 %>
              <td class="road"/>
            <% end %>
          <% end %>
        <% end %>
      </tr>    
    <% end %> 
  </tbody>
</table>

<br>

parking/app/views/spots/show.html.erb
<div class="row">
  <div class="col-sm-10 col-sm-offset-1">
    <h1>Reservations</h1>
    <br/>
    <div class="well">
			<%= form_for(@reservation, layout: 'inline') do |f| %>
			  <div class="actions">
					<%= f.number_field :spot_id, value: @spot.id, hidden: true %>
					<% if logged_in? %>
						<%= f.number_field :user_id, value: current_user.id, hidden: true %>
					<% end %>
			  	<%= f.datetime_select :requested_datetime, order: [:day, :month, :year], minute_step: 60, default: DateTime.now %>
			  	<%= f.number_field :time_range, style: 'margin-left:10px' %>
			    <%= f.submit 'Make Reservation', style: 'margin-left:20px' %>
			  </div>
			<% end %>
    </div>
  </div>
</div>

<div class="row" style="margin-bottom:20px"></div>

<div class="row">
  <div class="col-sm-10 col-sm-offset-1">

		<%- if @spot.reservations.none? %>
			<h3 id="table_message">No existing reservations</h3>
		<%- else %>
			<table align="center", class="table table-striped">
			  <thead>
			    <tr>
			    	<th class="text-center">Customer</th>
			      <th class="text-center">Reservation Date</th>
			      <th class="text-center">Duration (h)</th>  
			    </tr>
			  </thead>

			  <tbody>
					<% @spot.reservations.each do |reservation| %>
						<% user = User.find(reservation.user_id) %>
				  	<tr class="reservations_list_item">
				  		<td class="text-center"><%= user.name + " " + user.surname %></td>
				  		<td class="text-center"><%= reservation.requested_datetime.strftime("%x %H:%M") %></td>
							<td class="text-center"><%= reservation.time_range %></td>
							<% if logged_in? && reservation.user_id == current_user.id %>
								<td><%= link_to 'Cancel', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
							<% else %>
                <td/>
							<% end %>
				    </tr>
					<% end %>
				</tbody>
			</table>
		<% end %>	
	</div>
</div>