parking/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :spots
  resources :reservations
  get 'users/new'

  get 'uers/new'

  get 'main_controller/main'

  root 'spots#index'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users

end

parking/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Parking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  	
	<!-- Bootstrap core CSS -->
	<link href="https://blackrockdigital.github.io/startbootstrap-bare/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
	  <!-- Custom styles for this template -->
	<style>
	  body {
	    padding-top: 64px;
	  }
	  @media (min-width: 992px) {
	    body {
	      padding-top: 66px;
	    }
	  }
	</style>

</head>
<body>
 <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="/"><font size="5">Parking Manager</font></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <% if current_page?(:controller => 'spots') || current_page?('/')%>
              <li class="nav-item active">
            <% else %>
              <li class="nav-item">
            <% end %>
              <a class="nav-link" href="/spots">Home
              </a>
            </li>
            <% if current_page?(:controller => 'reservations') %>
              <li class="nav-item active">
            <% else %>
              <li class="nav-item">
            <% end %>
              <a class="nav-link" href="/reservations">Reservations</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Cars</a>
            </li>
            <li class="nav-item">
              <% if logged_in? %>
                <a class="nav-link" href="/users">Users</a>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
                     aria-expanded="false" data-toggle="collapse" data-target=".navbar-collapse">Account</a>
                  <div class="dropdown-menu">
                    <a class="dropdown-item" data-toggle="collapse" data-target=".navbar-collapse"><%= link_to "Profile", current_user %></a>
                    <a class="dropdown-item" data-toggle="collapse" data-target=".navbar-collapse"><%= link_to "Settings", edit_user_path(current_user) %></a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" data-toggle="collapse" data-target=".navbar-collapse"><%= link_to "Log out", logout_path, method: :delete %></a>
                  </div>
                </li>
              <% else %>
                <a class="nav-link" href="/login">Log in</a>
              <% end %>

            </li>
          </ul>
        </div>
      </div>
    </nav>

     <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>

<%= yield %>

<!-- Bootstrap core JavaScript -->
<script src="https://blackrockdigital.github.io/startbootstrap-bare/vendor/jquery/jquery.min.js"></script>
<script src="https://blackrockdigital.github.io/startbootstrap-bare/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>
</html>